### ISSUE TITLE
Web page assumption graph is missing

### ISSUE THREAD

**Issue by jefft0** [zb95/2016-ABAPlus#8]
Steps to reproduce: 

* Follow the instructions to run django and view the web page at http://127.0.0.1:8000 .
* Enter the simple ABA framework `myAsm(a).` and click Load.

Expected result: A graph with a dot labelled by `{a}` similar to the official web page at http://www-abaplus.doc.ic.ac.uk

Actual result: The graph is missing.

Does it work for you when you to a fresh installation of 2016-ABAPlus? Maybe there are some missing image or template files?

**Comment by zb95** [comment]
Thanks for pointing it out!
JavaScript and CSS files are part of the "static" files. The reason why they couldn't be loaded was because the server wasn't running in debug mode. When the debug mode is disabled, Django expects these files to be served by the production web server. 
I have now re-enabled the debug mode, so that the static files are served by Django's built-in development server.
Obviously, the development server isn't adequate for production.

**Comment by jefft0** [comment]
Thanks for the quick fix!
